### ISSUE TITLE
Tunnel mode not working.

### ISSUE THREAD

**Issue by psychoLK** [iamtrazy/bash-xray-script#6]
Hello, This is a great project thank you very much for spending your time on this. 😀
I have a small issue. Since the project moved from xtls-rprx-direct to xtls-rprx-vision netch stopped working. (There is no option to enable Vision on netch). I understand there are benefits from moving to vision but beaing able to use tunnel insted of proxy is really useful. Can you please provide a revition of the code that support xtls-rprx-direct.
Thank you.

**Comment by iamtrazy** [comment]
netch is outdated and unmaintained. use sing-box or clash meta for tun usage.
